version: 2.1
jobs:
  build:
    parameters:
      golangci-lint-version:
        type: string
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>

      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck
      # - run:
      #     name: Run tests
      #     command: go test -v
workflows:
  default_workflow:
    jobs:
      - build:
          golangci-lint-version: "1.49.0"
