version: 2.1
jobs:
  build:
    parameters:
      go-version:
        type: string
      golangci-lint-version:
        type: string
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.19.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v<< parameters.golangci-lint-version >>
      - run:
          name: Check GolangCI-Lint
          command: golangci-lint --version
      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --tests
      - run:
          name: Install StaticCheck
          command: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run:
          name: Run StaticCheck
          command: staticcheck -go << parameters.golangci-lint-version >> ./...

      # - run:
      #     name: Run tests
      #     command: go test -v
workflows:
  default_workflow:
    jobs:
      - build:
          go-version: "1.19"
          golangci-lint-version: "1.49.0"
